default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: uishots_development
  username: bkzl

test:
  <<: *default
  database: uishots_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
